name: eventsystem
version: '1.20.1'
main: me.marc3308.kmseventsystem.Eventsystem
depend: [zerotrust]
api-version: '1.21'

commands:
  saveevents:
    description: saves the events
  loadevents:
    description: load the events
  event:
    description: create/edit/delete event zones
  joinverstecken:
    description: joins a open verstechspiel

